"""empty message

Revision ID: 73188a32bdf7
Revises: ccab166e9cf3
Create Date: 2024-03-09 13:27:49.106260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73188a32bdf7'
down_revision = 'ccab166e9cf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
